theme: minima
title: Test Explorations
author: Nisha Unnikrishnanunny
description: In my journey to understand all the basics of testing, tools/technologies used and how Automation can increase the efficiency but without forgetting the base
